"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Cliente_1 = require("./Cliente");
const Empregado_1 = require("./Empregado");
const Pessoa_1 = require("./Pessoa");
let pessoa1 = new Pessoa_1.Pessoa("Paulo Jefferson Mendes Oliveira", 26, "São Paulo", "Boituva", "0");
pessoa1.apresentar();
let pessoa2 = new Pessoa_1.Pessoa("Silvia Mendes", 45, "São Paulo", "São Paulo", "0");
pessoa2.apresentar();
let cliente = new Cliente_1.Cliente("Matheus Carvalho", 45, "São Paulo", "São Paulo", true, "0");
cliente.apresentar();
cliente.verificarAssinatura();
console.log(cliente.getCpf());
cliente.setCpf("00000000");
console.log(cliente.getCpf());
let empregado = new Empregado_1.Empregado("João Paulo", 20, "São Paulo", "Santos", "0");
empregado.apresentar();
empregado.contrato();
